#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

# $Id$
module Sparkql
  class Parser < Racc::Parser

  include Sparkql::ParserTools
  include Sparkql::ParserCompatibility
  
##### State transition tables begin ###

racc_action_table = [
    36,    14,    15,    44,    45,    35,    46,    47,    48,    14,
    22,    32,    33,    34,    37,    38,    39,    40,    41,    36,
    17,    16,    23,    50,    35,    51,    10,    11,    14,   -35,
    32,    33,    34,    37,    38,    39,    40,    41,    36,    17,
    16,    62,    75,    35,    66,    63,    76,    14,    57,    32,
    33,    34,    37,    38,    39,    40,    41,    36,    18,    19,
    58,    61,    35,    72,    10,    11,    14,   nil,    32,    33,
    34,    37,    38,    39,    40,    41,    36,    14,   nil,    44,
    45,    35,    46,    47,    48,    14,   nil,    32,    33,    34,
    37,    38,    39,    40,    41,    36,   nil,   nil,    36,   nil,
    35,   nil,   nil,    35,   nil,   nil,    32,    33,    34,    32,
    33,    34,    36,   nil,     8,   nil,     9,    35,    10,    11,
    14,    14,   nil,    32,    33,    34,     8,   nil,     9,   nil,
    10,    11,    14,     9,   nil,    10,    11,    14,     9,   nil,
    10,    11,    14,     9,   nil,    10,    11,    14 ]

racc_action_check = [
    18,    19,     1,    19,    19,    18,    19,    19,    19,    18,
    13,    18,    18,    18,    18,    18,    18,    18,    18,    22,
    21,    21,    15,    21,    22,    22,    22,    22,    22,    28,
    22,    22,    22,    22,    22,    22,    22,    22,    58,     2,
     2,    52,    67,    58,    58,    52,    67,    58,    29,    58,
    58,    58,    58,    58,    58,    58,    58,    63,     6,     6,
    30,    43,    63,    59,    63,    63,    63,   nil,    63,    63,
    63,    63,    63,    63,    63,    63,    76,    61,   nil,    61,
    61,    76,    61,    61,    61,    76,   nil,    76,    76,    76,
    76,    76,    76,    76,    76,    35,   nil,   nil,    36,   nil,
    35,   nil,   nil,    36,   nil,   nil,    35,    35,    35,    36,
    36,    36,    57,   nil,     0,   nil,     0,    57,     0,     0,
     0,    57,   nil,    57,    57,    57,     9,   nil,     9,   nil,
     9,     9,     9,     8,   nil,     8,     8,     8,    16,   nil,
    16,    16,    16,    17,   nil,    17,    17,    17 ]

racc_action_pointer = [
   109,     2,    34,   nil,   nil,   nil,    55,   nil,   126,   121,
   nil,   nil,   nil,     3,   nil,    22,   131,   136,    -2,   -10,
   nil,    15,    17,   nil,   nil,   nil,   nil,   nil,    17,    36,
    53,   nil,   nil,   nil,   nil,    93,    96,   nil,   nil,   nil,
   nil,   nil,   nil,    49,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    33,   nil,   nil,   nil,   nil,   110,    36,    55,
   nil,    66,   nil,    55,   nil,   nil,   nil,    34,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    74,   nil ]

racc_action_default = [
    -2,   -55,    -1,    -3,    -4,    -5,   -55,    -8,   -55,   -55,
   -13,   -14,   -15,   -55,   -23,   -55,   -55,   -55,   -55,   -55,
    -9,   -55,   -55,    78,   -10,   -11,    -6,   -16,   -17,   -18,
   -55,   -34,   -39,   -40,   -41,   -55,   -55,   -44,   -45,   -46,
   -47,   -48,    -7,   -55,   -49,   -50,   -51,   -52,   -53,   -54,
   -12,   -19,   -55,   -24,   -26,   -27,   -28,   -55,   -55,   -55,
   -43,   -55,   -20,   -55,   -36,   -37,   -21,   -55,   -29,   -31,
   -32,   -33,   -42,   -38,   -25,   -22,   -55,   -30 ]

racc_goto_table = [
    27,    30,     2,    31,    43,    68,    49,    20,    56,    53,
     1,    21,    26,    42,    28,    24,    25,    29,    52,    67,
    59,    60,   nil,    77,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    69,    30,    64,    70,    65,   nil,    73,   nil,    49,    56,
    74,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    69,    30,
   nil,    70 ]

racc_goto_check = [
    11,    14,     2,    18,    20,    19,    10,     3,     6,    17,
     1,     2,     7,     8,    12,     3,     3,    13,    15,    16,
    18,    18,   nil,    19,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    11,    14,    18,    18,    10,   nil,    20,   nil,    10,     6,
    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11,    14,
   nil,    18 ]

racc_goto_pointer = [
   nil,    10,     2,    -1,   nil,   nil,   -14,    -6,    -6,   nil,
   -13,   -18,    -4,    -1,   -17,    -4,   -39,   -13,   -15,   -53,
   -15 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,   nil,   nil,     7,
    12,    54,    71,   nil,    13,   nil,   nil,   nil,    55,   nil,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 22, :_reduce_none,
  0, 22, :_reduce_2,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  3, 24, :_reduce_6,
  3, 24, :_reduce_7,
  1, 24, :_reduce_none,
  2, 26, :_reduce_9,
  3, 25, :_reduce_10,
  3, 25, :_reduce_11,
  3, 30, :_reduce_12,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_18,
  3, 31, :_reduce_19,
  4, 31, :_reduce_20,
  3, 33, :_reduce_21,
  4, 33, :_reduce_22,
  1, 35, :_reduce_none,
  1, 36, :_reduce_none,
  3, 36, :_reduce_25,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_28,
  1, 37, :_reduce_none,
  3, 37, :_reduce_30,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  3, 34, :_reduce_36,
  3, 34, :_reduce_37,
  3, 29, :_reduce_38,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  3, 39, :_reduce_42,
  2, 39, :_reduce_43,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none ]

racc_reduce_n = 55

racc_shift_n = 78

racc_token_table = {
  false => 0,
  :error => 1,
  :UMINUS => 2,
  :OPERATOR => 3,
  :RANGE_OPERATOR => 4,
  :UNARY_CONJUNCTION => 5,
  :CONJUNCTION => 6,
  :LPAREN => 7,
  :RPAREN => 8,
  :STANDARD_FIELD => 9,
  :CUSTOM_FIELD => 10,
  :KEYWORD => 11,
  :COMMA => 12,
  :INTEGER => 13,
  :DECIMAL => 14,
  :CHARACTER => 15,
  :DATE => 16,
  :DATETIME => 17,
  :TIME => 18,
  :BOOLEAN => 19,
  :NULL => 20 }

racc_nt_base = 21

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "UMINUS",
  "OPERATOR",
  "RANGE_OPERATOR",
  "UNARY_CONJUNCTION",
  "CONJUNCTION",
  "LPAREN",
  "RPAREN",
  "STANDARD_FIELD",
  "CUSTOM_FIELD",
  "KEYWORD",
  "COMMA",
  "INTEGER",
  "DECIMAL",
  "CHARACTER",
  "DATE",
  "DATETIME",
  "TIME",
  "BOOLEAN",
  "NULL",
  "$start",
  "target",
  "expressions",
  "expression",
  "conjunction",
  "unary_conjunction",
  "field",
  "condition",
  "range",
  "group",
  "function",
  "literal",
  "literal_function",
  "literal_list",
  "function_name",
  "function_args",
  "literal_function_args",
  "function_arg",
  "literals",
  "literal_function_arg",
  "rangeable" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

def _reduce_2(val, _values, result)
 result = 0 
    result
end

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values, result)
 result = tokenize_expression(val[0], val[1],val[2]) 
    result
end

def _reduce_7(val, _values, result)
 result = tokenize_expression(val[0], val[1], val[2]) 
    result
end

# reduce 8 omitted

def _reduce_9(val, _values, result)
 result = tokenize_unary_conjunction(val[0], val[1]) 
    result
end

def _reduce_10(val, _values, result)
 result = tokenize_conjunction(val[0], val[1],val[2]) 
    result
end

def _reduce_11(val, _values, result)
 result = tokenize_conjunction(val[0], val[1],val[2]) 
    result
end

def _reduce_12(val, _values, result)
 result = tokenize_group(val[1]) 
    result
end

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

def _reduce_18(val, _values, result)
 result = tokenize_list(val[0]) 
    result
end

def _reduce_19(val, _values, result)
 result = tokenize_function(val[0], []) 
    result
end

def _reduce_20(val, _values, result)
 result = tokenize_function(val[0], val[2]) 
    result
end

def _reduce_21(val, _values, result)
 result = tokenize_function(val[0], []) 
    result
end

def _reduce_22(val, _values, result)
 result = tokenize_function(val[0], val[2]) 
    result
end

# reduce 23 omitted

# reduce 24 omitted

def _reduce_25(val, _values, result)
 result = tokenize_function_args(val[0], val[2]) 
    result
end

# reduce 26 omitted

# reduce 27 omitted

def _reduce_28(val, _values, result)
 result = tokenize_field_arg(val[0]) 
    result
end

# reduce 29 omitted

def _reduce_30(val, _values, result)
 result = tokenize_function_args(val[0], val[2]) 
    result
end

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

def _reduce_36(val, _values, result)
 result = tokenize_multiple(val[0], val[2]) 
    result
end

def _reduce_37(val, _values, result)
 result = tokenize_multiple(val[0], val[2]) 
    result
end

def _reduce_38(val, _values, result)
 result = tokenize_multiple(val[0], val[2]) 
    result
end

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

def _reduce_42(val, _values, result)
 result = val[1] 
    result
end

def _reduce_43(val, _values, result)
 result = tokenize_literal_negation(val[1]) 
    result
end

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Sparkql


# END PARSER
