#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.8
# from Racc grammer file "".
#

require 'racc/parser.rb'

# $Id$
module Sparkql
  class Parser < Racc::Parser

  include Sparkql::ParserTools
  include Sparkql::ParserCompatibility
  
##### State transition tables begin ###

racc_action_table = [
    50,     7,    43,     9,    10,    23,    24,    26,    27,    29,
    30,    31,    21,    44,    23,    24,    26,    27,    29,    30,
    31,    23,    24,    26,    27,    29,    30,    31,     6,    45,
     7,    54,     9,    10,     6,    53,     7,    42,     9,    10,
    35,    36,    18,    38,    39,    35,    36,   nil,    38,    39,
     7,   nil,     9,    10,     7,   nil,     9,    10,    12,    13,
   nil,    41,    23,    24,    26,    14,    15,    12,    13 ]

racc_action_check = [
    43,     6,    22,     6,     6,    43,    43,    43,    43,    43,
    43,    43,    14,    33,    14,    14,    14,    14,    14,    14,
    14,    53,    53,    53,    53,    53,    53,    53,     7,    37,
     7,    46,     7,     7,     0,    46,     0,    18,     0,     0,
    45,    45,    11,    45,    45,    15,    15,   nil,    15,    15,
    13,   nil,    13,    13,    12,   nil,    12,    12,    17,    17,
   nil,    17,    44,    44,    44,     5,     5,     1,     1 ]

racc_action_pointer = [
    29,    62,   nil,   nil,   nil,    62,    -6,    23,   nil,   nil,
   nil,    42,    47,    43,     1,    32,   nil,    53,    37,   nil,
   nil,   nil,    -5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     1,   nil,   nil,   nil,    17,   nil,   nil,
   nil,   nil,   nil,    -8,    49,    27,    23,   nil,   nil,   nil,
   nil,   nil,   nil,     8,   nil,   nil ]

racc_action_default = [
    -2,    -1,    -3,    -4,    -5,   -39,   -39,   -39,    -8,   -13,
   -14,   -39,   -39,   -39,   -39,   -39,    -9,   -39,   -39,   -11,
   -10,   -20,   -39,   -28,   -29,   -25,   -30,   -31,    -6,   -32,
   -33,   -34,   -15,   -16,   -17,   -35,   -36,   -39,   -37,   -38,
    -7,   -12,    56,   -39,   -39,   -39,   -39,   -21,   -24,   -23,
   -18,   -26,   -27,   -39,   -19,   -22 ]

racc_goto_table = [
    37,    25,    47,     1,    33,    32,    34,    16,    22,    46,
    17,    40,    55,    19,    20,    28,    11,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    52,    51 ]

racc_goto_check = [
    17,    16,    15,     2,    11,    10,    12,     3,    13,    14,
     2,     8,    15,     3,     3,     7,     1,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    17,    16 ]

racc_goto_pointer = [
   nil,    16,     3,     1,   nil,   nil,   nil,     1,    -4,   nil,
    -9,   -10,    -8,    -6,   -34,   -41,   -13,   -15 ]

racc_goto_default = [
   nil,   nil,   nil,     2,     3,     4,     5,   nil,   nil,     8,
    49,   nil,   nil,   nil,   nil,   nil,    48,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 21, :_reduce_none,
  0, 21, :_reduce_2,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  3, 23, :_reduce_6,
  3, 23, :_reduce_7,
  1, 23, :_reduce_none,
  2, 25, :_reduce_9,
  3, 24, :_reduce_10,
  3, 24, :_reduce_11,
  3, 29, :_reduce_12,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_16,
  1, 27, :_reduce_none,
  3, 32, :_reduce_18,
  4, 32, :_reduce_19,
  1, 33, :_reduce_none,
  1, 34, :_reduce_none,
  3, 34, :_reduce_22,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 31, :_reduce_none,
  3, 31, :_reduce_26,
  3, 28, :_reduce_27,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none ]

racc_reduce_n = 39

racc_shift_n = 56

racc_token_table = {
  false => 0,
  :error => 1,
  :UMINUS => 2,
  :OPERATOR => 3,
  :RANGE_OPERATOR => 4,
  :UNARY_CONJUNCTION => 5,
  :CONJUNCTION => 6,
  :LPAREN => 7,
  :RPAREN => 8,
  :STANDARD_FIELD => 9,
  :CUSTOM_FIELD => 10,
  :KEYWORD => 11,
  :COMMA => 12,
  :INTEGER => 13,
  :DECIMAL => 14,
  :CHARACTER => 15,
  :DATE => 16,
  :DATETIME => 17,
  :BOOLEAN => 18,
  :NULL => 19 }

racc_nt_base = 20

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "UMINUS",
  "OPERATOR",
  "RANGE_OPERATOR",
  "UNARY_CONJUNCTION",
  "CONJUNCTION",
  "LPAREN",
  "RPAREN",
  "STANDARD_FIELD",
  "CUSTOM_FIELD",
  "KEYWORD",
  "COMMA",
  "INTEGER",
  "DECIMAL",
  "CHARACTER",
  "DATE",
  "DATETIME",
  "BOOLEAN",
  "NULL",
  "$start",
  "target",
  "expressions",
  "expression",
  "conjunction",
  "unary_conjunction",
  "field",
  "condition",
  "range",
  "group",
  "literal",
  "literal_list",
  "function",
  "function_name",
  "function_args",
  "function_arg",
  "literals",
  "rangeable" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

def _reduce_2(val, _values, result)
 result = 0 
    result
end

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

def _reduce_6(val, _values, result)
 result = tokenize_expression(val[0], val[1],val[2]) 
    result
end

def _reduce_7(val, _values, result)
 result = tokenize_expression(val[0], val[1], val[2]) 
    result
end

# reduce 8 omitted

def _reduce_9(val, _values, result)
 result = tokenize_unary_conjunction(val[0], val[1]) 
    result
end

def _reduce_10(val, _values, result)
 result = tokenize_conjunction(val[0], val[1],val[2]) 
    result
end

def _reduce_11(val, _values, result)
 result = tokenize_conjunction(val[0], val[1],val[2]) 
    result
end

def _reduce_12(val, _values, result)
 result = tokenize_group(val[1]) 
    result
end

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

def _reduce_16(val, _values, result)
 result = tokenize_list(val[0]) 
    result
end

# reduce 17 omitted

def _reduce_18(val, _values, result)
 result = tokenize_function(val[0], []) 
    result
end

def _reduce_19(val, _values, result)
 result = tokenize_function(val[0], val[2]) 
    result
end

# reduce 20 omitted

# reduce 21 omitted

def _reduce_22(val, _values, result)
 result = tokenize_function_args(val[0], val[2]) 
    result
end

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

def _reduce_26(val, _values, result)
 result = tokenize_multiple(val[0], val[2]) 
    result
end

def _reduce_27(val, _values, result)
 result = tokenize_multiple(val[0], val[2]) 
    result
end

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Sparkql


# END PARSER
